#!/usr/bin/env sh
alias ka="killall" \
	..2='cd ../..' \
	..3='cd ../../..' \
	..4='cd ../../../..' \
	..5='cd ../../../../..' \
	..6='cd ../../../../../..' \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -lahN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
	passpush="pass git add . && pass git commit -m "New account" && pass git push" \
	vpn='nordvpn' \
	pdf='zathura' \
	topydo='cd ~/notes/todotxt/ && topydo' \
	todo='cd ~/notes/todotxt/ && topydo'


command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}

# Logging of command line entry
log_bash_persistent_history()
{
  if [ "$(id -u)" -ne 0 ]; then
    echo "$(date "+%Y-%m-%d.%H:%M:%S") $(pwd) $(history 1)" >> \
          ~/.logs/bash-history/$(date "+%Y-%m-%d").log;
  fi
}

run_on_prompt_command()
{
  log_bash_persistent_history
}

export PROMPT_COMMAND='run_on_prompt_command'
