#!/usr/bin/env sh
alias ka="killall" \
	..2='cd ../..' \
	..3='cd ../../..' \
	..4='cd ../../../..' \
	..5='cd ../../../../..' \
	..6='cd ../../../../../..' \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -lahN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
	vpn='nordvpn' \
	topydo='cd ~/Documents/notes/todotxt/ && topydo' \
	todo='cd ~/Documents/notes/todotxt/ && topydo'\
	repos='cd ~/Documents/repos' \

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

# open files with vim
vf() { fzf | xargs -r -I % "$EDITOR" % ;}

# find and change directories
fd() { cd $(find . -type d -printf '%d\t%P\n' | sort -r -nk1 | cut -f2- | fzf);}

# read pdf and epub files
# book() { [ -z "$1" ] && find . -name "*.pdf" -o -name "*.epub" -type f | fzf | xargs -r -I % "$READER" % ; [ -n "$1" ] && zathura "$1"; }

# books() { cd "$HOME/Documents/books" && book;}
